### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Allicce** [alzbetamyskova/NaDobrouNoc#2]
-

- [x]  scroll button
- [x]  prev / next  button to fairy tail components  || random button to fairy tail components
- [ ]  button back
- [x]  image to every fairy tail
- [x]  firebase
- [x]  filter
- [x]  player 
- [ ]   click to keyword  === filter this category???? 
- [x]  background image
- [ ]  implement keyboard (arrow left / right / enter)
- [x]  responsive design

**Comment by alzbetamyskova** [comment]
Některé komponenty vynechány z důvodu časové náročnosti, ostatní udělány v minulých 4-5 commitech.
